resources:
- name: ci-test-repo
  type: git
  source:
    uri: git@github.com:triangle-stream/ci-test.git
    branch: main
    private_key: ((git_private_key)) # Variabile per la chiave SSH

jobs:
- name: check-progetto1-and-update
  plan:
  - get: ci-test-repo
    trigger: true # Scatta al rilevamento di modifiche
    version: every
  - task: create-test-file
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: alpine
      inputs:
      - name: ci-test-repo
      outputs:
      - name: updated-repo
      run:
        path: sh
        args:
        - -exc
        - |
          cd ci-test-repo/progetto1
          if [ "$(git diff --name-only HEAD^ HEAD | grep progetto1/)" ]; then
            echo "Modifiche rilevate in progetto1"
            cd ../progetto3
            echo "Test file created at $(date)" > test.txt
            cp -r ../* ../updated-repo/
          else
            echo "Nessuna modifica rilevata in progetto1"
          fi
  - put: ci-test-repo
    params:
      repository: updated-repo
      rebase: true

