resources:
- name: ci-test-repo
  type: git
  source:
    uri: git@github.com:triangle-stream/ci-test.git
    branch: main
    private_key: ((git_private_key))

jobs:
- name: check-progetto1-and-update
  plan:
  - get: ci-test-repo
    trigger: true
    version: every
  - task: create-test-file
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: alpine/git
      inputs:
      - name: ci-test-repo
      outputs:
      - name: updated-repo
      run:
        path: sh
        args:
        - -exc
        - |
          cd ci-test-repo
          
          # Verifica modifiche in progetto1
          if [ "$(git diff --name-only HEAD^ HEAD | grep progetto1/)" ]; then
            echo "Modifiche rilevate in progetto1"
            
            # Crea il file test.txt in progetto3
            cd progetto3
            echo "Test file created at $(date)" > test.txt
            cd ..
            
            # Commit e push delle modifiche
            git config --global user.email "ci@trianglecdn.it"
            git config --global user.name "Concourse CI"
            git add progetto3/test.txt
            git commit -m "Aggiunto test.txt dopo modifiche in progetto1"
          else
            echo "Nessuna modifica rilevata in progetto1"
          fi
  - put: ci-test-repo
    params:
      repository: updated-repo
      rebase: true

